name: Test CI
on:
    pull_request:
        branches: [ "*" ]
    workflow_dispatch:
jobs:
  test_before_pr :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
    